# An Ansible playbook to deploy the Perfios scripts project

- name: configure servre with install docker
  hosts: all
  become: true
  become_method: sudo
  tags:
    - deploy
  roles:
    - role: install_docker

- name: setup k8s environment
  hosts: all
  become: true
  become_method: sudo
  tags:
    - deploy
  roles:
    - role: setup_k8s